### ISSUE TITLE
The Star Junction Burger Shot Icon cannot be unlocked (TBoGT)

### ISSUE THREAD

**Issue by Fredster247** [GTAmodding/GTAIV-Issues-List#157] opened 2024-06-15 18:58 UTC
As the title suggests, in The Ballad of Gay Tony portion of the game, the Burger Shot icon on the minimap located in Star Junction cannot be unlocked. 

![Skärmbild (496)](https://github.com/GTAmodding/GTAI
![Skärmbild (495)](https://github.com/GTAmodding/GTAIV-Issues-List/assets/172931025/7ccddca4-c931-427b-b4f0-094c7b34553e)
![Skärmbild (497)](https://github.com/GTAmodding/GTAIV-Issues-List/assets/172931025/e25a5f40-108d-41e1-9600-b58e6cfefe2e)

**Comment by Tomasak** [comment] 2024-06-16 07:59
dupe of https://github.com/GTAmodding/GTAIV-Issues-List/issues/34

**Closed as not planned by Tomasak** 2024-06-16 07:59 UTC
