### ISSUE TITLE
The minigame doesn't work

### ISSUE THREAD

**Issue by Dr1Ft3RXII** [GTAmodding/GTAIV-Issues-List#133] opened 2024-01-04 21:27 UTC
When starting a new game in the TBOGT dlc during the first mission, you cannot drink a shot and the glass on the bar does not respawn, just like on the upper floor there is no npct for the champagne zeroing mini game, which logically means you cannot play it (despite progress and returning to the club later, the error is not fixed) I would like to ask you to repair this function and check other once have not been broken (and in LC there are several restaurants that do not have an icon but can be used, something could be done about it :)) thank you

**Comment by Tomasak** [comment] 2024-01-14 18:02
cannot reproduce. Are you using other mods?
as for restaurants i think its dupe of #34

**Comment by ghost** [comment] 2024-02-07 18:55
bumping, also have the same issue as OP. no shots, no champagne contest, dancing works as normal though. only mods installed are FusionFix, ColAccel and Radio Downgrader, using GTA IV: Complete Edition on the most recent patch.

**Comment by Tomasak** [comment] 2024-02-07 20:49
thats a bug with alternative dialogue option. it sohuld be fixed with latest fusion fix.

**Closed as completed** 2024-02-13 15:30 UTC
